### ISSUE TITLE
Server join broken

### ISSUE THREAD

**Issue by f4n74z14** [ThomasOM/Pledge#7] opened 2023-04-07 04:38 UTC
Hello! After the latest changes, joining the game broke for me.

Stacktrace:
<pre>
[10:45:03] [Netty Server IO #1/WARN]: java.lang.reflect.InvocationTargetException
[10:45:03] [Netty Server IO #1/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:45:03] [Netty Server IO #1/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:45:03] [Netty Server IO #1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:45:03] [Netty Server IO #1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:45:03] [Netty Server IO #1/WARN]: 	at dev.thomazz.pledge.util.ChannelHelper.encodeAndCompress(ChannelHelper.java:19)
[10:45:03] [Netty Server IO #1/WARN]: 	at dev.thomazz.pledge.network.handler.PacketFrameOutboundHeadHandler.flush(PacketFrameOutboundHeadHandler.java:88)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:38)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext$16.run(AbstractChannelHandlerContext.java:756)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[10:45:03] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[10:45:03] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:750)
[10:45:03] [Netty Server IO #1/WARN]: Caused by: java.lang.ClassCastException: io.netty.buffer.PooledUnsafeDirectByteBuf cannot be cast to net.minecraft.server.v1_12_R1.Packet
[10:45:03] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.PacketEncoder.encode(PacketEncoder.java:17)
[10:45:03] [Netty Server IO #1/WARN]: 	... 19 more
</pre>

Tested on: git-Paper-1618 (MC: 1.12.2) ; git-Paper-498 (MC: 1.19.4)

Also the problem persists with and w/o ViaVersion, ProtocolLib.

### Thanks!

**Comment by ScatDev** [comment] 2023-04-12 22:35
I also started getting this

**Comment by ThomasOM** [comment] 2023-04-13 22:26
I am currently working on a fix for this, you can use version 2.2 for the moment

**Comment by ThomasOM** [comment] 2023-04-13 23:18
As it stands now I am unable to reproduce it, on paper current paper version, no plugins with only pledge active

**Comment by ThomasOM** [comment] 2023-04-13 23:22
I force deployed a new build to the maven repository, let me know if this fixes it.
If not please provide me with the following information:
- Bungeecoord enabled / disabled
- Compression threshold
- Last server log file

**Comment by ThomasOM** [comment] 2023-04-15 01:49
I've confirmed this as fixed on the latest build with another user, let me know if this is also resolved on the latest build

**Comment by f4n74z14** [comment] 2023-04-19 16:50
Hello! Sorry, misclick.

I've tested on the lastest build (2.3 from repo) and the problem still persists for me

1. BungeeCord mode is disabled.
2. network-compression-threshold=0
3. The lastest log:
<pre>
[23:48:46] [Server thread/INFO]: Starting minecraft server version 1.12.2
[23:48:46] [Server thread/INFO]: Loading properties
[23:48:46] [Server thread/WARN]: resource-pack-hash is deprecated and found along side resource-pack-sha1. resource-pack-hash will be ignored.
[23:48:46] [Server thread/INFO]: Default game type: SURVIVAL
[23:48:46] [Server thread/INFO]: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[23:48:46] [Server thread/INFO]: Debug logging is disabled
[23:48:46] [Server thread/INFO]: Server Ping Player Sample Count: 12
[23:48:46] [Server thread/INFO]: Using 4 threads for Netty based IO
[23:48:46] [Server thread/INFO]: Generating keypair
[23:48:47] [Server thread/INFO]: Starting Minecraft server on *:10100
[23:48:47] [Server thread/ERROR]: Ambiguous plugin name `WorldGuard' for files `plugins\WorldGuard.jar' and `plugins\worldguard-bukkit-6.2.2.jar' in `plugins'
[23:48:47] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[23:48:47] [Server thread/INFO]: [WGFixer] Loading WGFixer v1.0
[23:48:47] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.9;caf0ad9
[23:48:47] [Server thread/INFO]: [AutoParkour] Loading AutoParkour v3.0
[23:48:47] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.10.6
[23:48:47] [Server thread/INFO]: [PlugMan] Loading PlugMan v2.1.7
[23:48:47] [Server thread/INFO]: [spark] Loading spark v1.9.42
[23:48:47] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v4.6.0-23w06a-SNAPSHOT
[23:48:47] [Server thread/INFO]: [ViaVersion] ViaVersion 4.6.0-23w06a-SNAPSHOT is now loaded, waiting for boot. (late-bind)
[23:48:47] [Server thread/INFO]: [WorldBorder] Loading WorldBorder v1.8.7
[23:48:47] [Server thread/INFO]: [WorldGuardRestrictor] Loading WorldGuardRestrictor v1.0
[23:48:47] [Server thread/INFO]: [Vault] Loading Vault v1.7.2-b107
[23:48:47] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0
[23:48:47] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v6.2.2-SNAPSHOT;
[23:48:47] [Server thread/INFO]: [NoCheatPlus] Loading NoCheatPlus v3.17-SNAPSHOT-Updated-b69
[23:48:47] [Server thread/INFO]: [NoCheatPlus] onLoad: Early set up of static API, configuration, logging.
[23:48:47] [Server thread/INFO]: [NoCheatPlus] Logging system initialized.
[23:48:47] [Server thread/INFO]: [NoCheatPlus] Detected Minecraft version: 1.12.2
[23:48:47] [Server thread/INFO]: [VimeChat] Loading VimeChat v4.1
[23:48:47] [Server thread/INFO]: [VimeOptimizator] Loading VimeOptimizator v1.0
[23:48:47] [Server thread/INFO]: [WGExtender] Loading WGExtender v1.0
[23:48:47] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:48:47] [Server thread/INFO]: [Vault] Enabling Vault v1.7.2-b107
[23:48:47] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[23:48:47] [Server thread/INFO]: [Vault] Enabled Version 1.7.2-b107
[23:48:47] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.4.0
[23:48:47] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[23:48:47] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[23:48:47] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[23:48:47] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[23:48:47] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[23:48:47] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[23:48:47] [Server thread/INFO]: Preparing level "world"
[23:48:47] [Server thread/INFO]: -------- World Settings For [world] --------
[23:48:47] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[23:48:47] [Server thread/INFO]: Item Despawn Rate: 1200
[23:48:47] [Server thread/INFO]: Item Merge Radius: 5.5
[23:48:47] [Server thread/INFO]: View Distance: 6
[23:48:47] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: false
[23:48:47] [Server thread/INFO]: Arrow Despawn Rate: 1200
[23:48:47] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[23:48:47] [Server thread/INFO]: Mob Spawn Range: 4
[23:48:47] [Server thread/INFO]: Cactus Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Cane Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Melon Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Mushroom Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Pumpkin Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Sapling Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Wheat Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: NetherWart Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Vine Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Cocoa Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Random Lighting Updates: false
[23:48:47] [Server thread/INFO]: Entity Activation Range: An 6 / Mo 8 / Mi 2 / Tiv true
[23:48:47] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[23:48:47] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[23:48:47] [Server thread/INFO]: Max TNT Explosions: 100
[23:48:47] [Server thread/INFO]: Structure Info Saving: true
[23:48:47] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[23:48:47] [Server thread/INFO]: Experience Merge Radius: 7.0
[23:48:47] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[23:48:47] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[23:48:47] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[23:48:47] [Server thread/INFO]: Item Despawn Rate: 1200
[23:48:47] [Server thread/INFO]: Item Merge Radius: 5.5
[23:48:47] [Server thread/INFO]: View Distance: 6
[23:48:47] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: false
[23:48:47] [Server thread/INFO]: Arrow Despawn Rate: 1200
[23:48:47] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[23:48:47] [Server thread/INFO]: Mob Spawn Range: 4
[23:48:47] [Server thread/INFO]: Cactus Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Cane Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Melon Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Mushroom Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Pumpkin Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Sapling Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Wheat Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: NetherWart Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Vine Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Cocoa Growth Modifier: 70%
[23:48:47] [Server thread/INFO]: Random Lighting Updates: false
[23:48:47] [Server thread/INFO]: Entity Activation Range: An 6 / Mo 8 / Mi 2 / Tiv true
[23:48:47] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[23:48:47] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[23:48:47] [Server thread/INFO]: Max TNT Explosions: 100
[23:48:47] [Server thread/INFO]: Structure Info Saving: true
[23:48:47] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[23:48:47] [Server thread/INFO]: Experience Merge Radius: 7.0
[23:48:47] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[23:48:47] [Server thread/INFO]: Preparing start region for level 0 (Seed: -8278790340730946275)
[23:48:47] [Server thread/INFO]: Preparing start region for level 1 (Seed: -7624938259479785965)
[23:48:48] [Server thread/INFO]: [WGFixer] Enabling WGFixer v1.0
[23:48:48] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.9;caf0ad9
[23:48:48] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[23:48:48] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R2 as the Bukkit adapter
[23:48:48] [Server thread/INFO]: [AutoParkour] Enabling AutoParkour v3.0
[23:48:48] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.10.6
[23:48:48] [Server thread/INFO]: [PlugMan] Enabling PlugMan v2.1.7
[23:48:48] [Server thread/INFO]: [spark] Enabling spark v1.9.42
[23:48:48] [Server thread/INFO]: [spark] Using Bukkit scheduler for tick monitoring
[23:48:48] [Server thread/INFO]: [spark] Registered PlaceholderAPI placeholders
[23:48:48] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.6.0-23w06a-SNAPSHOT
[23:48:48] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading 1.12 -> 1.13 mappings...
[23:48:48] [Via-Mappingloader-1/INFO]: [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
[23:48:48] [Via-Mappingloader-2/INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
[23:48:48] [Via-Mappingloader-3/INFO]: [ViaVersion] Loading 1.14 -> 1.15 mappings...
[23:48:48] [Via-Mappingloader-4/INFO]: [ViaVersion] Loading 1.15 -> 1.16 mappings...
[23:48:48] [Via-Mappingloader-1/INFO]: [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
[23:48:48] [Via-Mappingloader-5/INFO]: [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
[23:48:48] [Via-Mappingloader-2/INFO]: [ViaVersion] Loading 1.17 -> 1.18 mappings...
[23:48:48] [Via-Mappingloader-4/INFO]: [ViaVersion] Loading 1.18 -> 1.19 mappings...
[23:48:48] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading 1.19 -> 1.19.3 mappings...
[23:48:48] [Via-Mappingloader-1/INFO]: [ViaVersion] Loading 1.19.3 -> 1.19.4 mappings...
[23:48:48] [Server thread/INFO]: [WorldBorder] Enabling WorldBorder v1.8.7
[23:48:48] [Server thread/INFO]: [WorldBorder] [CONFIG] Using elliptic/round border, knockback of 3.0 blocks, and timer delay of 5.
[23:48:48] [Server thread/INFO]: [WorldBorder] [CONFIG] Border-checking timed task started.
[23:48:48] [Server thread/INFO]: [WorldBorder] For reference, the main world's spawn location is at X: -724,0 Y: 4,0 Z: -465,0
[23:48:48] [Server thread/INFO]: [WorldGuardRestrictor] Enabling WorldGuardRestrictor v1.0
[23:48:48] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.2.2-SNAPSHOT;
[23:48:48] [Server thread/INFO]: [WorldGuard] (world) Поджигание TNT РАЗРЕШЕНО.
[23:48:48] [Server thread/INFO]: [WorldGuard] (world) Зажигалки РАЗРЕШЕНЫ.
[23:48:48] [Server thread/INFO]: [WorldGuard] (world) Огонь лавы отключен.
[23:48:48] [Server thread/INFO]: [WorldGuard] (world) Распространение огня НЕОГРАНИЧЕНО.
[23:48:48] [Server thread/INFO]: [WorldGuard] Загрузка конфигурации для мира 'world'
[23:48:48] [Server thread/INFO]: [WorldGuard] (world_nether) Поджигание TNT РАЗРЕШЕНО.
[23:48:48] [Server thread/INFO]: [WorldGuard] (world_nether) Зажигалки РАЗРЕШЕНЫ.
[23:48:48] [Server thread/INFO]: [WorldGuard] (world_nether) Огонь лавы отключен.
[23:48:48] [Server thread/INFO]: [WorldGuard] (world_nether) Распространение огня НЕОГРАНИЧЕНО.
[23:48:48] [Server thread/INFO]: [WorldGuard] Загрузка конфигурации для мира 'world_nether'
[23:48:48] [Server thread/INFO]: [WorldGuard] Загрузка данных региона...
[23:48:48] [Server thread/INFO]: [NoCheatPlus] Enabling NoCheatPlus v3.17-SNAPSHOT-Updated-b69
[23:48:49] [Server thread/INFO]: [NoCheatPlus] McAccess set to: 1.12-1.12.2 / Spigot-CB-1.12_R1
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Added block-info for Minecraft 1.5 blocks.
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Added block-info for Minecraft 1.6.1 blocks.
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Added block-info for Minecraft 1.7.2 blocks.
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Added block-info for Minecraft 1.8 blocks.
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Added block-info for Minecraft 1.9 blocks.
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Added block-info for Minecraft 1.10 blocks.
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Added block-info for Minecraft 1.11 blocks.
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Added block-info for Minecraft 1.12 blocks.
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Applied block patches for multi client protocol support: water_lily, soil, grass_path, shulker_box
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Update block-info: Block shape patch for multi client protocol support around 1.7.x - 1.16.x.
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): moving_piston
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_TUBE_CORAL
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_TUBE_CORAL_WALL_FAN
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_BRAIN_CORAL
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_BRAIN_CORAL_WALL_FAN
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_BUBBLE_CORAL
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_BUBBLE_CORAL_WALL_FAN
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_FIRE_CORAL
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_FIRE_CORAL_WALL_FAN
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_HORN_CORAL
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_HORN_CORAL_WALL_FAN
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_TUBE_CORAL_FAN
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_BRAIN_CORAL_FAN
[23:48:49] [Server thread/WARN]: [NoCheatPlus] Bad block id (compatibility.blocks.overrideflags): DEAD_BUBBLE_CORAL_FAN
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Inventory checks: FastConsume is available, disabled InstantEat.
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Adding packet level hooks for ProtocolLib (MC 1.12.2)...
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Confirm teleport packet available (via name): TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0]
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Available (and activated) packet level hooks: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Force disable FastHeal on Minecraft 1.9 and later.
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Version 3.17-SNAPSHOT-Updated-b69 is enabled.
[23:48:49] [Server thread/INFO]: [VimeChat] Enabling VimeChat v4.1
[23:48:49] [Server thread/INFO]: [VimeChat] Disabling VimeChat v4.1
[23:48:49] [Server thread/INFO]: [VimeOptimizator] Enabling VimeOptimizator v1.0
[23:48:49] [Server thread/INFO]: [VimeOptimizator] Started up Pledge
[23:48:49] [Server thread/INFO]: [WGExtender] Enabling WGExtender v1.0
[23:48:49] [Server thread/INFO]: Done (1,703s)! For help, type "help" or "?"
[23:48:49] [Server thread/INFO]: Using default channel type
[23:48:49] [Server thread/INFO]: Timings Reset
[23:48:49] [Craft Scheduler Thread - 1/INFO]: [NoCheatPlus] Added hook: AllViolations(NCP) [1.0].
[23:48:49] [Craft Scheduler Thread - 1/INFO]: [NoCheatPlus] Added hook: ViolationFrequency(NCP) [1.0].
[23:48:49] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.12.2 (340)
[23:48:49] [Server thread/WARN]: [ViaVersion] This version of Minecraft is extremely outdated and support for it has reached its end of life. You will still be able to run Via on this Minecraft version, but we are unlikely to provide any further fixes or help with problems specific to legacy Minecraft versions. Please consider updating to give your players a better experience and to avoid issues that have long been fixed.
[23:48:49] [Server thread/WARN]: [ViaVersion] You are running an outdated Java version, please consider updating it to at least Java 17 (your version is 1.8.0_352). At some point in the future, ViaVersion will no longer be compatible with this version of Java.
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Post-enable running...
[23:48:49] [Server thread/INFO]: [NoCheatPlus] Post-enable finished.
[23:48:49] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[23:48:49] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: shell
[23:48:49] [Server thread/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[23:48:50] [Server thread/WARN]: [ViaVersion] There is a newer plugin version available: 4.6.2, you're on: 4.6.0-23w06a-SNAPSHOT
[23:48:56] [User Authenticator #1/INFO]: UUID of player f4n74z14 is dc862636-6056-386d-a05d-50c4b768a100
[23:48:57] [Server thread/INFO]: f4n74z14[/127.0.0.1:50353] logged in with entity id 1 at ([world]-721.6039311467415, 15.407981917462884, -432.233108868952)
[23:48:57] [Server thread/INFO]: f4n74z14 lost connection: Internal Exception: java.lang.reflect.InvocationTargetException
[23:48:57] [Server thread/INFO]: f4n74z14 left the game
</pre>

**Comment by ThomasOM** [comment] 2023-04-20 23:29
Hello, this should be resolved in update 2.4. Let me know if you're still experiencing issues.

**Comment by f4n74z14** [comment] 2023-04-21 22:11
Yup, now it works but incompatible with ProtocolLib. 😵

**Comment by ThomasOM** [comment] 2023-04-23 21:02
First exception seems very weird since it seems like a handshake listener instead of a login listener is found even though the login listener is called? The second issue should be fixed in 8e0dff8, feel free to verify if your issue is resolved.

**Comment by f4n74z14** [comment] 2023-04-25 17:05
> First exception seems very weird since it seems like a handshake listener instead of a login listener is found even though the login listener is called?

Yes, that weird, but sometimes it happens.

**Comment by gbomexify** [comment] 2023-04-26 04:59
onJoin
`[04:56:23] [Netty Epoll Server IO #1/WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.IllegalStateException: Handler has not been activated yet!
	at dev.thomazz.pledge.PlayerHandler.createNextFrame(PlayerHandler.java:173) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_212]
	at dev.thomazz.pledge.PledgeImpl.getOrCreateFrame(PledgeImpl.java:189) ~[?:?]
	at dev.thomazz.pledge.PledgeImpl.getOrCreateFrame(PledgeImpl.java:183) ~[?:?]
	
[04:56:27] [Netty Epoll Server IO #4/WARN]: A task raised an exception.
java.lang.RuntimeException: java.lang.NullPointerException
	at dev.thomazz.pledge.PlayerHandler.lambda$tickEnd$1(PlayerHandler.java:131) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [server.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [server.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server.jar:1.8.8-R0.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at dev.thomazz.pledge.network.PacketFrameOutboundHeadHandler.drain(PacketFrameOutboundHeadHandler.java:109) ~[?:?]
	at dev.thomazz.pledge.PlayerHandler.lambda$tickEnd$1(PlayerHandler.java:129) ~[?:?]
	... 4 more`

**Comment by ThomasOM** [comment] 2023-04-26 05:37
@gbomexify Create a new issue for this

**Comment by ThomasOM** [comment] 2023-05-29 03:07
Closing this now, if any other problems are encountered feel free to create another issue

**Closed by ThomasOM** 2023-05-29 03:07 UTC
Labels: bug
